#!/usr/bin/env python
#coding:utf8
import datetime
import json
import os
import sys

import MySQLdb
import urllib2

from db import mysql
from conf import param


class ZabbixApi(object):
    def __init__(self,username="sijie",password="sijie",server="http://127.0.0.1/api_jsonrpc.php",host_list='/etc/work_server_config',db_host="",db_username="",db_password=""):
        self.username = username
        self.password = password
        self.server = server
        self.list = host_list
        self.db_host = db_host
        self.db_username = db_username
        self.db_passwprd = db_password
        self.log = self.log()
        self.db = self.db()
        self.header = {"Content-Type": "application/json"}
        self.token = self.login_token()

    def _reponse(self,data):
        request = urllib2.Request(self.server,data)
        for key in self.header:
            request.add_header(key, self.header[key])
        try:
            result = urllib2.urlopen(request)
        except urllib2.URLError as e:
            print "Failed, Please Check :", e.code
            sys.exit(10)
        return result

    def log(self):
        f = open("./action.log","w+")
        return f

    def logger(self,msg):
        nowTime=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        self.log.write("%s: %s\n" %(nowTime,msg))

    def login_token(self):
        data = json.dumps(param.param['user']['login']) % (self.username, self.password)
        result =self._reponse(data)
        response = json.loads(result.read())
        result.close()
        return response['result']

    ### 这里有待优化，例如 json.dumps(param.param['user']['login']) %(self.username,self.password)这样的形式
    def create_host(self,hostname,ip,groupid=2,templateid=10001):
        param.param['host']['create']['params']['host']=hostname
        param.param['host']['create']['params']['interfaces'][0]['ip']=ip
        param.param['host']['create']['params']['groups'][0]['groupid']=groupid
        param.param['host']['create']['params']['templates'][0]['templateid'] = templateid
        param.param['host']['create']['auth']=self.token
        data = json.dumps(param.param["host"]["create"])
        result = self._reponse(data)

    def db(self):
        return mysql()


if __name__ == "__main__":
    zabbix = ZabbixApi(server="https://monitor.kuainiujinke.com/api_jsonrpc.php",db_username="logstash",db_password="logstash",db_host="10.66.233.131")
    zabbix.diff_ip()
    zabbix.remove_unavaiable_host()